seed: 21
model: 'unet++'
dataset: 'augmix'
batch_size: 16
epochs: 60
loss: 'DiceCE'
optimizer: 'madgrad'
learning_rate: 1e-4
max_lr: 1e-3
min_lr: 1e-5

scheduler_step: 5
weight_decay: 1e-6
log_step: 25
checkpoint: 'all'

wandb_name: 'augmix'
load_path: 'test'
is_load: False
is_crf: True
is_tta: True
data_dir: '/opt/ml/segmentation/input/data'
saved_dir: '/opt/ml/checkpoints'
inference_dir: '/opt/ml/checkpoints/exp1'
save_name: 'unet++_iou'
submission_dir: '/opt/ml/submission'
