# Recommended not to change
FRAMEWORKS_AVAILABLE: ["torchvision", "segmentation_models_pytorch"]

# Recommended not to change
MODELS_AVAILABLE:
    torchvision: ["fcn_resnet50",
                  "fcn_resnet101",
                  "deeplabv3_resnet50",
                  "deeplabv3_resnet101",
                  "deeplabv3_mobilenet_v3_large",
                  "lraspp_mobilenet_v3_large"]
    segmentation_models.pytorch: ["UNet", 
                                  "UNetPlusPlus"]

CRITERION_AVAILABLE:
    PYTORCH: ["CrossEntropy"]
    
OPTIMIZER_AVAILABLE:
    PYTORCH: ["Adam", "AdamW", "SGD"]


SELECTED:
    # IF you use torchvision model
    FRAMEWORK: "torchvision"
    MODEL: "lraspp_mobilenet_v3_large" # also used for submission save.
    MODEL_CFG:
        pretrained: True
      
    # # 2. IF you use smp model
    # # smp.create_model(**cfg["SELECTED"]["MODEL_CFG"]) 형태로 사용하기 때문에
    # # MODEL_CFG 아래는 소문자가 좋습니다. (PRETRAINED -> pretrained)
    # FRAMEWORK: "segmentation_models.pytorch"
    # MODEL: "UNetPlusPlus" # also used for submission save.
    # MODEL_CFG: # 이하 예시 - 모델에 따른 백본이나 기학습 가중치를 set_smp_model에서 지정해도 될듯
    #     pretrained: 'imagenet' # advpros 등
    #         encoder_name: 'efficinetnet-b4' 
    #         # 이하 고정 값
    #         in_channels: 3
    #         classes: 11
    
    CRITERION: "CrossEntropy"
    CRITERION_CFG:
        label_smoothing: 0.0
        
    OPTIMIZER: "Adam"
    OPTIMIZER_CFG:
        weight_decay: 1e-6


SEED: 21

EXPERIMENTS:
    NUM_EPOCHS: 1
    BATCH_SIZE: 16
    LEARNING_RATE: 1e-4
    NUM_WORKERS: 4
    VAL_EVERY: 1
    
    
    WNB_TURN_ON: True
    WNB_INIT:
        entity: "ai_tech_level2-cv-18"
        project: "seunghun_T2042"
        name: "lraspp_mobilenet_v3_large" # recommended to change
    
    
    SAVED_DIR: 
        BEST_MODEL: "./saved"
        SUBMISSION: "./submission"
    
    
    TRAIN_TRANS: # ToTensorV2 는 기본으로 들어가있고 Albumentation 의 augmentation 이용
        GridDistortion: 
            p: 1.0
        RandomGridShuffle:
            p: 1.0
        RandomResizedCrop:
            height: 512
            width: 512
            p: 1.0
        GridDropout:
            p: 1.0
        ElasticTransform:
            p: 1.0
        HorizontalFlip:
            p: 0.5
    TEST_n_VAL_TRANS: # ToTensorV2 는 기본으로 들어가있음.
    
    
    TTA_TURN_ON: False
    TTA_CFG:
        Rotate90: 
            angles: [0, 180]
            

DATASET:
    PATH: "../segmentation/input/data"
    ANNS_FILE_NAME: "train_all.json"
    TRAIN_FILE_NAME: "train.json"
    VAL_FILE_NAME: "val.json"
    TEST_FILE_NAME: "test.json"
    NUM_CLASSES: 11

